/**
 * Gallery Highlights - the festival archive.
 *
 * Presentation lives in components/events/. To add or remove a photograph,
 * edit this array only: the 3D composition, focus order, metadata HUD and the
 * static fallback all derive from it.
 *
 * Drop the matching files into public/events_posters/. Any file that is missing
 * renders as a neutral archive placeholder instead of breaking the scene.
 */

export type GalleryItem = {
  id: number;
  eventId?: string;
  image: string;
  title: string;
  category: string;
  venue: string;
  year: number;
  alt: string;
  description: string;
  minTeam?: number;
  maxTeam?: number;
  winnerCash?: number | string;
  runnerUpCash?: number | string;
  totalCash?: number | string;
  prizesRemarks?: string;
};

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    eventId: "panache",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/PANACHE.webp",
    title: "Panache",
    category: "Flagship Events - Team",
    venue: "Campus",
    year: 2026,
    alt: "Panache at Sabrang 2026",
    description: "Haute Couture Runway Show | Prize Pool: ₹35,000",
    minTeam: 6,
    maxTeam: 20,
    winnerCash: 21000,
    runnerUpCash: 14000,
    totalCash: 35000,
  },
  {
    id: 2,
    eventId: "sync",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/DANCE_BATTLE.webp",
    title: "SYNC",
    category: "Flagship Events - Team",
    venue: "Campus",
    year: 2026,
    alt: "SYNC at Sabrang 2026",
    description: "Group Dance Showdown | Prize Pool: ₹35,000",
    minTeam: 8,
    maxTeam: 25,
    winnerCash: 21000,
    runnerUpCash: 14000,
    totalCash: 35000,
  },
  {
    id: 3,
    eventId: "bandjam",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/BANDJAM.webp",
    title: "Band Jam",
    category: "Flagship Events - Team",
    venue: "Campus",
    year: 2026,
    alt: "Band Jam at Sabrang 2026",
    description: "Battle of the Bands | Prize Pool: ₹25,000",
    minTeam: 4,
    maxTeam: 10,
    winnerCash: 15000,
    runnerUpCash: 10000,
    totalCash: 25000,
  },
  {
    id: 4,
    eventId: "persona",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/art.webp",
    title: "Persona",
    category: "Flagship Events - Solo / Duo",
    venue: "Campus",
    year: 2026,
    alt: "Persona at Sabrang 2026",
    description: "Solo/Duo Performance | Prize Pool: ₹15,000",
    minTeam: 1,
    maxTeam: 1,
    winnerCash: 9000,
    runnerUpCash: 6000,
    totalCash: 15000,
  },
  {
    id: 5,
    eventId: "step_up",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/STEPUP.webp",
    title: "Step Up",
    category: "Flagship Events - Solo / Duo",
    venue: "Campus",
    year: 2026,
    alt: "Step Up at Sabrang 2026",
    description: "Solo Dance Competition | Prize Pool: ₹15,000",
    minTeam: 1,
    maxTeam: 1,
    winnerCash: 9000,
    runnerUpCash: 6000,
    totalCash: 15000,
  },
  {
    id: 6,
    eventId: "echoes_of_noor",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/echoesofnoor.webp",
    title: "Echoes of Noor",
    category: "Flagship Events - Solo / Duo",
    venue: "Campus",
    year: 2026,
    alt: "Echoes of Noor at Sabrang 2026",
    description: "Sufi Night & Acoustic Melodies | Prize Pool: ₹15,000",
    minTeam: 1,
    maxTeam: 2,
    winnerCash: 9000,
    runnerUpCash: 6000,
    totalCash: 15000,
  },
  {
    id: 7,
    eventId: "versevaad",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/VERSVAAD.webp",
    title: "Verse Vaad",
    category: "Flagship Events - Solo / Duo",
    venue: "Campus",
    year: 2026,
    alt: "Verse Vaad at Sabrang 2026",
    description: "Poetry Slam & Literary Debates | Prize Pool: ₹15,000",
    minTeam: 1,
    maxTeam: 2,
    winnerCash: 9000,
    runnerUpCash: 6000,
    totalCash: 15000,
  },
  {
    id: 8,
    eventId: "bgmi",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/bgmi.webp",
    title: "BGMI",
    category: "Non-Flagship - Esports",
    venue: "Campus",
    year: 2026,
    alt: "BGMI at Sabrang 2026",
    description: "Battlegrounds Mobile India Tournament | Prize Pool: ₹15,000",
    minTeam: 4,
    maxTeam: 5,
    winnerCash: 9000,
    runnerUpCash: 6000,
    totalCash: 15000,
  },
  {
    id: 9,
    eventId: "freefire",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/freefire.webp",
    title: "Free Fire",
    category: "Non-Flagship - Esports",
    venue: "Campus",
    year: 2026,
    alt: "Free Fire at Sabrang 2026",
    description: "Free Fire Mobile Esports Tournament | Prize Pool: ₹12,000",
    minTeam: 4,
    maxTeam: 5,
    winnerCash: 7000,
    runnerUpCash: 5000,
    totalCash: 12000,
  },
  {
    id: 10,
    eventId: "valorant",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/valo.webp",
    title: "Valorant",
    category: "Non-Flagship - Esports",
    venue: "Campus",
    year: 2026,
    alt: "Valorant at Sabrang 2026",
    description: "5v5 PC Tactical FPS Tournament | Prize Pool: ₹10,000",
    minTeam: 5,
    maxTeam: 5,
    winnerCash: 6000,
    runnerUpCash: 4000,
    totalCash: 10000,
  },
  {
    id: 11,
    eventId: "rang_manch",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/convo.webp",
    title: "Rang Manch",
    category: "Non-Flagship - Other Events",
    venue: "Campus",
    year: 2026,
    alt: "Rang Manch at Sabrang 2026",
    description: "Stage Play & Theatrical Drama | Prize Pool: ₹15,000",
    minTeam: 8,
    maxTeam: 15,
    winnerCash: 9000,
    runnerUpCash: 6000,
    totalCash: 15000,
  },
  {
    id: 12,
    eventId: "courtroom",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/courtroom.webp",
    title: "Court Room",
    category: "Non-Flagship - Other Events",
    venue: "Campus",
    year: 2026,
    alt: "Court Room at Sabrang 2026",
    description: "Mock Trial & Legal Battle | Prize Pool: ₹10,000",
    minTeam: 2,
    maxTeam: 4,
    winnerCash: 6000,
    runnerUpCash: 4000,
    totalCash: 10000,
  },
  {
    id: 13,
    eventId: "bidding",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/deal.webp",
    title: "Bidding Before Wicket",
    category: "Non-Flagship - Other Events",
    venue: "Campus",
    year: 2026,
    alt: "Bidding Before Wicket at Sabrang 2026",
    description: "IPL Mock Cricket Auction | Prize Pool: ₹10,000",
    minTeam: 3,
    maxTeam: 5,
    winnerCash: 6000,
    runnerUpCash: 4000,
    totalCash: 10000,
  },
  {
    id: 14,
    eventId: "dumb_show",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/dumb.webp",
    title: "Dumb Show",
    category: "Non-Flagship - Other Events",
    venue: "Campus",
    year: 2026,
    alt: "Dumb Show at Sabrang 2026",
    description: "Mime & Dumb Charades | Prize Pool: ₹7,000",
    minTeam: 3,
    maxTeam: 3,
    winnerCash: 4000,
    runnerUpCash: 3000,
    totalCash: 7000,
  },
  {
    id: 15,
    eventId: "vaad_vivaad",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/convo.webp",
    title: "Vaad Vivaad",
    category: "Non-Flagship - Other Events",
    venue: "Campus",
    year: 2026,
    alt: "Vaad Vivaad at Sabrang 2026",
    description: "Conventional Debate Competition (Solo) | Prize Pool: ₹6,000",
    minTeam: 1,
    maxTeam: 1,
    winnerCash: 3500,
    runnerUpCash: 2500,
    totalCash: 6000,
  },
  {
    id: 16,
    eventId: "face_off",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/STEPUP.webp",
    title: "Face Off",
    category: "Non-Flagship - Other Events",
    venue: "Campus",
    year: 2026,
    alt: "Face Off at Sabrang 2026",
    description: "Street Dance Face Off (Solo) | Prize Pool: ₹12,000",
    minTeam: 1,
    maxTeam: 1,
    winnerCash: "6,000 + 6,000*",
    totalCash: 12000,
    prizesRemarks: "2 styles, no runner-up; ₹6,000 per category",
  },
  {
    id: 17,
    eventId: "anime_quiz",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/focus.webp",
    title: "Anime Quiz",
    category: "Non-Flagship - Other Events",
    venue: "Campus",
    year: 2026,
    alt: "Anime Quiz at Sabrang 2026",
    description: "Ultimate Otaku Trivia Challenge | Prize Pool: ₹5,000",
    minTeam: 2,
    maxTeam: 2,
    winnerCash: 3000,
    runnerUpCash: 2000,
    totalCash: 5000,
  },
  {
    id: 18,
    eventId: "art_relay",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/art.webp",
    title: "Art Relay",
    category: "Activities - Gifts & Hampers",
    venue: "Campus",
    year: 2026,
    alt: "Art Relay at Sabrang 2026",
    description: "Collaborative Fine Arts Challenge | Gifts & Hampers",
    minTeam: 1,
    maxTeam: 1,
    prizesRemarks: "Gifts / Hampers",
  },
  {
    id: 19,
    eventId: "clay_modelling",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/clay.webp",
    title: "Clay Modelling",
    category: "Activities - Gifts & Hampers",
    venue: "Campus",
    year: 2026,
    alt: "Clay Modelling at Sabrang 2026",
    description: "Sculptural Creativity & Craft | Gifts & Hampers",
    minTeam: 1,
    maxTeam: 1,
    prizesRemarks: "Gifts / Hampers",
  },
  {
    id: 20,
    eventId: "chai_pe_charcha",
    image: "https://res.cloudinary.com/eprhemvt/image/upload/f_auto,q_auto/v1787060200/sabrang-2026/events_posters/convo.webp",
    title: "Chai Pe Charcha",
    category: "Activities - Gifts & Hampers",
    venue: "Campus",
    year: 2026,
    alt: "Chai Pe Charcha at Sabrang 2026",
    description: "Conversations & Open Mic Session | Gifts & Hampers",
    minTeam: 1,
    maxTeam: 1,
    prizesRemarks: "Gifts / Hampers",
  }
];
